version: '3.4'

services:
  # Servicio de la base de datos PostgreSQL
  - type: pserv
    name: collecti-stamp-db
    runtime: docker
    image: postgres:14.9-alpine
    instanceSize: micro
    persistentDisk: true
    envVars:
      POSTGRES_PASSWORD: postgres

  # Servicio web de la aplicación Django
  - type: web
    name: collecti-stamp-web
    runtime: docker
    buildCommand: |
      apk add --no-cache git postgresql-dev gcc libc-dev
      apk add --no-cache gcc g++ make libffi-dev python3-dev build-base
      pip install gunicorn psycopg2 ipdb ipython
      git clone https://github.com/Lenient-Enterprise/collecti-stamp.git /app
      pip install -r /app/collecti_stamp/requirements.txt
      cd /app/collecti_stamp
      python manage.py collectstatic --noinput
    startCommand: gunicorn -w 5 collecti_stamp.wsgi --timeout=500 -b 0.0.0.0:5000
    dependsOn:
      - collecti-stamp-db

  # Servicio de proxy Nginx
  - type: web
    name: collecti-stamp-nginx
    runtime: docker
    buildCommand: ADD docker-nginx.conf /etc/nginx/conf.d/default.conf
    startCommand: nginx -g "daemon off;"
    dependsOn:
      - collecti-stamp-web

volumes:
  # Volumen para archivos estáticos
  - name: collecti-stamp-static
    mountPath: /app/collecti_stamp/static

networks:
  # Configuración de la red bridge
  - name: bridge
    type: bridge
    reservedPorts:
      - 8000

