name: Python application

on:
  push:
    branches:
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.9
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12
      - name: psycopg2 prerequisites
        run: sudo apt-get install libpq-dev
      - name: Install dependencies and config
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations (unnecessary)
        run: |
          cd collecti_stamp
          python manage.py migrate
      - name: Run tests
        run: |
          cd collecti_stamp
          ./manage.py test  --keepdb 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        if: github.ref == 'refs/heads/release'
        env:
          deploy_url: ${{secrets.RENDER_DEPLOY_HOOK_URL}}
        run: |
          curl "$deploy_url"